# Generated by Django 3.2 on 2022-06-01 10:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код покупателя')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Логин')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
            },
        ),
        migrations.CreateModel(
            name='Manual_measurements',
            fields=[
                ('measure_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код единицы измерения')),
                ('measure', models.CharField(max_length=30, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код стройматериала')),
                ('name', models.DateField(verbose_name='Наименование стройматериала')),
                ('weight', models.FloatField(verbose_name='Вес')),
                ('length', models.FloatField(verbose_name='Длина')),
                ('width', models.FloatField(verbose_name='Ширина')),
                ('height', models.FloatField(verbose_name='Высота')),
                ('price', models.CharField(max_length=30, verbose_name='Цена за единицу')),
            ],
            options={
                'verbose_name': 'Стройматериал',
                'verbose_name_plural': 'Стройматериалы',
            },
        ),
        migrations.CreateModel(
            name='Material_category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код категории')),
                ('name', models.DateField(verbose_name='Наименование категории')),
            ],
            options={
                'verbose_name': 'Категория стройматериала',
                'verbose_name_plural': 'Категории стройматериала',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код заказа')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='Дата заказа')),
                ('discount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Скидка')),
                ('delivery', models.FloatField(verbose_name='Стоимость доставки')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sale_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код продажи')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='Дата продажи')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
            },
        ),
        migrations.CreateModel(
            name='Saler',
            fields=[
                ('saler_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код продовца')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Логин')),
            ],
            options={
                'verbose_name': 'Продавец',
                'verbose_name_plural': 'Продавецы',
            },
        ),
        migrations.CreateModel(
            name='OrderMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.material', verbose_name='Номер стройматериала')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.order', verbose_name='Номер заказа')),
            ],
            options={
                'verbose_name': 'Корзина заказа',
                'verbose_name_plural': 'Корзины заказа',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.sale', verbose_name='Код продажи'),
        ),
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.material_category', verbose_name='Категория стройматериала'),
        ),
        migrations.AddField(
            model_name='material',
            name='measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.manual_measurements', verbose_name='Единица измерения'),
        ),
    ]
