# Generated by Django 3.2 on 2022-06-02 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='saler',
            name='address',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='saler',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата рождения'),
        ),
    ]
