# Generated by Django 3.2 on 2022-06-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_material_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='image',
            field=models.ImageField(blank=True, default='product/no_image.png', upload_to='product/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Наименование стройматериала'),
        ),
        migrations.AlterField(
            model_name='material_category',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Наименование категории'),
        ),
    ]
