# Generated by Django 3.2 on 2022-06-02 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0005_auto_20220602_2103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saler',
            options={'verbose_name': 'Продавец', 'verbose_name_plural': 'Продавцы'},
        ),
    ]
