# Generated by Django 3.2 on 2022-06-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0006_alter_saler_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='volume',
            field=models.FloatField(blank=True, null=True, verbose_name='Объем'),
        ),
        migrations.AlterField(
            model_name='material',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='material',
            name='length',
            field=models.FloatField(blank=True, null=True, verbose_name='Длина'),
        ),
        migrations.AlterField(
            model_name='material',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='material',
            name='width',
            field=models.FloatField(blank=True, null=True, verbose_name='Ширина'),
        ),
    ]
