# Generated by Django 3.2 on 2022-06-03 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0007_auto_20220602_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(blank=True, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='builder.sale', verbose_name='Код продажи'),
        ),
    ]
