# Generated by Django 3.2 on 2022-06-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0008_auto_20220603_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В обработке', 'В обработке'), ('Выполнен', 'Выполнен')], default='В обработке', max_length=14, verbose_name='Статус заказа'),
        ),
    ]
