# Generated by Django 3.2 on 2022-06-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.FloatField(default=1000, verbose_name='Стоимость доставки'),
        ),
    ]
