# Generated by Django 3.2 on 2022-06-03 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0010_alter_order_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='builder.material_category', verbose_name='Категория стройматериала'),
        ),
    ]
