# Generated by Django 3.2 on 2022-06-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0011_alter_material_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='price',
            field=models.FloatField(max_length=30, verbose_name='Цена за единицу'),
        ),
    ]
