# Generated by Django 3.2 on 2022-06-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0012_alter_material_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.FloatField(default=0, verbose_name='Стоимость заказа'),
        ),
    ]
