# Generated by Django 3.2 on 2022-06-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0013_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.FloatField(default='OrderMaterial.material.price*OrderMaterial.quantity', verbose_name='Стоимость заказа'),
        ),
    ]
